### ISSUE TITLE
Typo on line 63 in anykernel.sh

### ISSUE THREAD

**Issue by Zackptg5** [EAS-Project/AnyKernel2#2]
Present: $bin/sepolicy-inject -s init -t rootfs -c system -p module_load -P sepolicy_deb,ug;

Should be: $bin/sepolicy-inject -s init -t rootfs -c system -p module_load -P sepolicy_debug;

Keep up the great work!

**Comment by joshchoo** [comment]
Thank you very much @Zackptg5! Without your sharp eyes we would likely not have fixed this in a long long time :)

**Comment by joshchoo** [comment]
I've fixed pushed a fix with your authorship

**Comment by RenderBroken** [comment]
We need more people to be as keen as you. Thanks!
